-- Removing somebody from a household, without removing what they made (#127).
--
-- A member is what four tables record as the person who created a row —
-- `ingredient.created_by`, `recipe.created_by` and `.updated_by`,
-- `planned_batch.created_by`, `pantry_entry.added_by` — and the recipe list
-- and recipe screen join `member` to print that person's name. So DELETE was
-- never the right verb: for anybody who has actually used the app it either
-- breaks a foreign key or takes their recipes off the screen with them.
--
-- The first attempt at #127 refused to remove such a member at all, which
-- blocked the removal the issue asks for and, with it, the only move there is
-- — #127 defines moving somebody as removing them here and adding them there.
--
-- So removal is a stamp, not a delete. The row stays and keeps attributing
-- history; what goes is the household access it granted.
ALTER TABLE member ADD COLUMN removed_at TEXT;

-- `google_sub` is UNIQUE across the whole table, and the sub is the only thing
-- sign-in matches on. A removed member has to give theirs up — otherwise the
-- same person could never be added to another household, which is the second
-- half of a move.
--
-- Rather than rebuild `member` to make that UNIQUE conditional (four tables
-- point at it; a rebuild against the live database is not worth it), the live
-- column is rewritten to a tombstone and the real sub is kept here.
--
-- The tombstone has to be something Google can never issue. The first version
-- of this migration said `removed:<id>` was safe because a Google `sub` is a
-- decimal string — which Google does not promise. Its contract is any
-- case-sensitive ASCII string of up to 255 characters, so `removed:2` is a
-- legal account id, and reserving that shape would have locked a real person
-- out of the admin screen and left a parked row for them to collide with.
--
-- So the tombstone is outside that contract rather than inside it: U+2014 EM
-- DASH followed by the member id. It is not ASCII, so it is not a `sub`.
-- `src/google.ts::isGoogleSub` states that contract in one place, and both
-- sign-in and the admin form are held to it.
ALTER TABLE member ADD COLUMN removed_google_sub TEXT;
