import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

/**
 * Fixed browser entries, one DOM-typed build pipeline. Generated string modules
 * are committed so deployment ships the reviewed bytes; --check rejects stale
 * or missing output. No runtime Worker imports belong in these browser entries.
 *
 * Intake, shopping and the recipe screen's product picker keep their ES5
 * syntax floor and feature detection. The
 * splitter keeps its existing ES2019 target and DecompressionStream requirement
 * unchanged.
 */

const root = fileURLToPath(new URL("../", import.meta.url));
const target = `${root}src/generated`;
const checking = process.argv.includes("--check");

const entries = [
  { name: "recipe-image-split", target: "es2019", description: "The bundled splitter, served to the admin image screen as a script." },
  { name: "intake", target: "es5", description: "The bundled intake client, embedded on the server-rendered intake form." },
  { name: "shopping", target: "es5", description: "The bundled shopping client, embedded on the server-rendered shopping list." },
  { name: "recipe-products", target: "es5", description: "The bundled product picker, embedded on a recipe screen for the S-ostoslista household." },
];

for (const entry of entries) {
  const source = `src/client/${entry.name}.ts`;
  const path = `${target}/${entry.name}.ts`;
  const built = await esbuild.build({
    entryPoints: [`${root}${source}`],
    bundle: true,
    format: "iife",
    target: entry.target,
    platform: "browser",
    // Comments are the point of this repository, but not in the shipped bundle:
    // the source is what anybody reads, and the artifact is reviewed as a diff.
    minify: true,
    legalComments: "none",
    write: false,
    // The Worker's tsconfig would drag in Workers types; the browser build wants
    // the DOM. `npm run typecheck` is what checks either — this only transpiles.
    tsconfig: `${root}tsconfig.client.json`,
  });

  const output = built.outputFiles[0];
  if (output === undefined) throw new Error("esbuild produced no output");

  const module = [
    "// Generated by `npm run generate:client` from " + source + ".",
    "// Do not edit by hand. Committed on purpose, and `npm run check` fails when",
    "// it is stale — see scripts/build-client.mjs for why.",
    "",
    `/** ${entry.description} */`,
    `export default ${JSON.stringify(output.text)};`,
    "",
  ].join("\n");
  const bytes = Buffer.from(module);

  await mkdir(target, { recursive: true });

  if (checking) {
    let existing;
    try {
      existing = await readFile(path);
    } catch {
      throw new Error(
        `src/generated/${entry.name}.ts is missing; run npm run generate:client`,
      );
    }
    if (!existing.equals(bytes)) {
      throw new Error(
        `src/generated/${entry.name}.ts is stale; run npm run generate:client`,
      );
    }
  } else {
    await writeFile(path, bytes);
  }

  console.log(
    checking
      ? `${entry.name} bundle is current`
      : `Bundled ${entry.name} (${bytes.length} bytes)`,
  );
}
