import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

/**
 * Bundle the browser half of the recipe-image screen, and commit the result.
 *
 * There is exactly one thing in the app that runs in a browser and is more than
 * a few lines of inline script: the contact-sheet splitter, which had to move
 * out of the Worker because the Free plan gives a request 10 ms of CPU (see
 * `docs/adr/0005-the-worker-does-no-pixel-work.md`). It imports
 * `src/contact-sheet.ts` and `src/png.ts` directly, so the crop rules exist
 * once and `dev/check-contact-sheet.ts` still tests them under node — but those
 * files are TypeScript with `.ts` imports, which no browser will load.
 *
 * The output is **committed**, and `--check` fails when it is stale. That is
 * the pattern `assets/pwa/generated/*.png` already follows, and it is chosen
 * for the same reason: CI and the deploy job need no new build step, the
 * deployed bytes are the reviewed bytes, and a stale artifact is caught by
 * `npm run check` rather than discovered in production. The cost is having to
 * run `npm run generate:client` after touching the splitter, which the check
 * will remind anybody who forgets.
 *
 * It is written as a TypeScript module exporting the source as a string, rather
 * than as a `.js` file imported through a wrangler module rule. Wrangler's own
 * bundler claims `.js` for itself before any `Text` rule is consulted, so an
 * artifact with that extension cannot be imported as text at all — and a module
 * needs no rule, no glob and no new asset mechanism. `recipe-image-admin.ts`
 * serves the string with its own headers, like every other route.
 *
 * `es2019` because these are hand-written browser bytes with no transpilation
 * anywhere else in the app (issue #65), and because the screen's real floor is
 * `DecompressionStream` rather than syntax — the script feature-detects that
 * and says so. Anything old enough to choke on the syntax lacks the API too.
 */

const root = fileURLToPath(new URL("../", import.meta.url));
const entry = `${root}src/client/recipe-image-split.ts`;
const target = `${root}src/generated`;
const path = `${target}/recipe-image-split.ts`;
const checking = process.argv.includes("--check");

const built = await esbuild.build({
  entryPoints: [entry],
  bundle: true,
  format: "iife",
  target: "es2019",
  platform: "browser",
  // Comments are the point of this repository, but not in the shipped bundle:
  // the source is what anybody reads, and the artifact is reviewed as a diff.
  minify: true,
  legalComments: "none",
  write: false,
  // The Worker's tsconfig would drag in Workers types; the browser build wants
  // the DOM. `npm run typecheck` is what checks either — this only transpiles.
  tsconfig: `${root}tsconfig.client.json`,
});

const output = built.outputFiles[0];
if (output === undefined) throw new Error("esbuild produced no output");

const module = [
  "// Generated by `npm run generate:client` from src/client/recipe-image-split.ts.",
  "// Do not edit by hand. Committed on purpose, and `npm run check` fails when",
  "// it is stale — see scripts/build-client.mjs for why.",
  "",
  "/** The bundled splitter, served to the admin image screen as a script. */",
  `export default ${JSON.stringify(output.text)};`,
  "",
].join("\n");
const bytes = Buffer.from(module);

await mkdir(target, { recursive: true });

if (checking) {
  let existing;
  try {
    existing = await readFile(path);
  } catch {
    throw new Error(
      "src/generated/recipe-image-split.ts is missing; run npm run generate:client",
    );
  }
  if (!existing.equals(bytes)) {
    throw new Error(
      "src/generated/recipe-image-split.ts is stale; run npm run generate:client",
    );
  }
} else {
  await writeFile(path, bytes);
}

console.log(
  checking
    ? "Recipe-image splitter bundle is current"
    : `Bundled the recipe-image splitter (${bytes.length} bytes)`,
);
